export const messagingTaxonomy = [
  "AI and automation", "connected platform", "operational risk", "contractor safety", "sustainability and ESG", "compliance automation", "frontline and mobile", "analytics and intelligence", "workforce readiness", "supply-chain risk",
];

export const corporateSourceHierarchy = [
  { level: 1, label: "Primary filing or company release", examples: "SEC EDGAR, investor relations, official newsroom", use: "Transaction facts, dates, parties, consideration, management statements" },
  { level: 2, label: "Government or court record", examples: "FTC, DOJ, state registry, court docket", use: "Regulatory status, challenges, approvals, legal events" },
  { level: 3, label: "Approved trade reporting", examples: "EHS Today and named sector publications", use: "Discovery and sector context; facts traced back to primary sources" },
  { level: 4, label: "Analyst interpretation", examples: "Internal synthesis with named author and timestamp", use: "Implications only; never stored as transaction fact" },
];

export const monitoringJobs = [
  { name: "Competitor product surfaces", coverage: "16 mapped competitors", cadence: "Weekly", method: "Snapshot + semantic diff", status: "Mapped" },
  { name: "Official newsrooms", coverage: "Press releases and company announcements", cadence: "Daily", method: "RSS / sitemap / page monitor", status: "Mapped" },
  { name: "SEC EDGAR", coverage: "Public-company filings and exhibits", cadence: "Daily", method: "Official submissions and filing APIs", status: "Ready" },
  { name: "EHS Today watch", coverage: "Sector transactions and product news", cadence: "Daily", method: "Discovery monitor; primary-source confirmation required", status: "Mapped" },
];

export const changeContract = ["company_id", "page_url", "page_type", "captured_at", "content_hash", "previous_hash", "changed_terms", "messaging_tags", "source_excerpt", "review_status"];

export type CorporateEvent = {
  id: string;
  announcedAt: string;
  company: string;
  counterparty: string;
  type: "Acquisition" | "Investment" | "Separation";
  status: "Announced" | "Closed" | "Operating transition";
  domain: "Core EHS" | "Contractor Management" | "Sustainability" | "Occupational Health" | "Chemical & Product Compliance" | "Environmental Intelligence" | "Crisis Readiness";
  geography: string;
  headline: string;
  fact: string;
  strategicThesis: string;
  boardImplication: string;
  sourceName: string;
  sourceUrl: string;
  sourceTier: "Official company" | "Official investor" | "Regulatory filing";
};

export const corporateEvents: CorporateEvent[] = [
  {
    id: "novara-ensogo-2026",
    announcedAt: "2026-06-09",
    company: "Novara",
    counterparty: "Ensogo",
    type: "Acquisition",
    status: "Closed",
    domain: "Sustainability",
    geography: "North America + international",
    headline: "Novara acquires Ensogo",
    fact: "Novara announced the acquisition of Ensogo, an AI-native sustainability platform, expanding its AI capabilities, sustainability offering, and international footprint.",
    strategicThesis: "Connect operational risk and sustainability data inside a focused high-risk-industry platform.",
    boardImplication: "Novara is extending beyond core safety workflows while retaining a high-risk-industry focus; integration evidence should now be monitored at the module and customer level.",
    sourceName: "Novara announcement",
    sourceUrl: "https://novara.com/blog/novara-acquires-ensogo-to-accelerate-ai-powered-operational-risk-management-and-sustainability-strategy/",
    sourceTier: "Official company",
  },
  {
    id: "novara-separation-2026",
    announcedAt: "2026-01-27",
    company: "Novara",
    counterparty: "KPA",
    type: "Separation",
    status: "Operating transition",
    domain: "Core EHS",
    geography: "North America",
    headline: "KPA separates Novara as an independent company",
    fact: "KPA separated its Flex and Risk Management Center software businesses into Novara, with KPA retaining its automotive focus and Novara serving high-risk industries.",
    strategicThesis: "Create sharper product, capital-allocation, and go-to-market focus around non-automotive operational risk.",
    boardImplication: "The relevant competitive entity is now Novara—not legacy KPA—when evaluating construction, manufacturing, utilities, and oil and gas.",
    sourceName: "Novara announcement",
    sourceUrl: "https://novara.com/blog/kpa-separates-businesses-launching-novara-to-serve-high-risk-industries/",
    sourceTier: "Official company",
  },
  {
    id: "enhesa-totalsds-2025",
    announcedAt: "2025-10-27",
    company: "Enhesa",
    counterparty: "TotalSDS",
    type: "Acquisition",
    status: "Closed",
    domain: "Chemical & Product Compliance",
    geography: "Global",
    headline: "Enhesa acquires TotalSDS",
    fact: "Enhesa acquired TotalSDS to connect regulatory intelligence, chemical hazard information, and SDS authoring and management workflows.",
    strategicThesis: "Move from regulatory intelligence into an end-to-end chemical-compliance operating workflow.",
    boardImplication: "Regulatory-content providers are moving downstream into execution software, increasing pressure on standalone SDS and product-stewardship tools.",
    sourceName: "Enhesa announcement",
    sourceUrl: "https://www.enhesa.com/resources/press/enhesa-acquires-totalsds/",
    sourceTier: "Official company",
  },
  {
    id: "veriforce-highwire-2025",
    announcedAt: "2025-10-22",
    company: "Veriforce",
    counterparty: "Highwire",
    type: "Acquisition",
    status: "Closed",
    domain: "Contractor Management",
    geography: "Global + U.S. construction",
    headline: "Veriforce acquires Highwire",
    fact: "Veriforce acquired Highwire, combining its global contractor network with Highwire's construction-focused prequalification, financial-risk, and field-safety capabilities.",
    strategicThesis: "Add capital-project and construction depth to a global contractor-management network.",
    boardImplication: "Contractor management is consolidating around network scale plus differentiated risk data, with data centers and advanced manufacturing named as expansion environments.",
    sourceName: "Veriforce announcement",
    sourceUrl: "https://veriforce.com/company/press-room/veriforce-acquires-highwire-expanding-leadership-in-contractor-risk-management",
    sourceTier: "Official company",
  },
  {
    id: "ideagen-safetystratus-2025",
    announcedAt: "2025-10-02",
    company: "Ideagen",
    counterparty: "SafetyStratus",
    type: "Acquisition",
    status: "Closed",
    domain: "Chemical & Product Compliance",
    geography: "Global",
    headline: "Ideagen acquires SafetyStratus",
    fact: "Ideagen acquired SafetyStratus to add specialized chemical inventory, radiation, hazardous-waste, and biosafety capabilities to its EHS portfolio.",
    strategicThesis: "Acquire specialized domain depth that broad EHS suites often lack.",
    boardImplication: "Ideagen is using targeted acquisitions to deepen regulated-industry workflows rather than relying only on horizontal platform breadth.",
    sourceName: "Ideagen announcement",
    sourceUrl: "https://www.ideagen.com/company/news/ideagen-acquires-safetystratus-adding-specialized-chemical-management-to-its-ehs-portfolio",
    sourceTier: "Official company",
  },
  {
    id: "ideagen-envirosuite-2025",
    announcedAt: "2025-08-22",
    company: "Ideagen",
    counterparty: "Envirosuite",
    type: "Acquisition",
    status: "Closed",
    domain: "Environmental Intelligence",
    geography: "Global",
    headline: "Ideagen completes Envirosuite acquisition",
    fact: "Ideagen completed the acquisition of Envirosuite, adding real-time monitoring and predictive analytics for noise, air, water, odour, vibration, and community impact.",
    strategicThesis: "Strengthen the environmental side of EHS with sensor-linked operational intelligence.",
    boardImplication: "Environmental monitoring is moving closer to core EHS suites, expanding the competitive surface into industrial IoT and predictive environmental risk.",
    sourceName: "Ideagen completion announcement",
    sourceUrl: "https://www.ideagen.com/company/news/ideagen-completes-acquisition-of-environmental--intelligence-company-envirosuite",
    sourceTier: "Official company",
  },
  {
    id: "ideagen-reactec-2025",
    announcedAt: "2025-08-18",
    company: "Ideagen",
    counterparty: "Reactec",
    type: "Acquisition",
    status: "Closed",
    domain: "Core EHS",
    geography: "Global",
    headline: "Ideagen acquires Reactec",
    fact: "Ideagen acquired Reactec, adding wearables and analytics for vibration, dust, noise, and proximity hazards in high-risk industries.",
    strategicThesis: "Link worker exposure data and proactive hazard sensing to established EHS workflows.",
    boardImplication: "Connected-worker and exposure-monitoring capabilities are becoming an acquisition path into predictive safety.",
    sourceName: "Ideagen announcement",
    sourceUrl: "https://www.ideagen.com/company/news/ideagen-expands-safety-solutions-with-reactec-acquisition",
    sourceTier: "Official company",
  },
  {
    id: "ecoonline-d4h-2025",
    announcedAt: "2025-06-24",
    company: "EcoOnline",
    counterparty: "D4H",
    type: "Acquisition",
    status: "Closed",
    domain: "Crisis Readiness",
    geography: "Global",
    headline: "EcoOnline acquires D4H",
    fact: "EcoOnline acquired D4H to add crisis-readiness and response software connected to its EHS, chemical-safety, and sustainability products.",
    strategicThesis: "Extend prevention and compliance workflows into real-time crisis coordination and resilience.",
    boardImplication: "The EHS suite boundary is expanding into business continuity and emergency operations, creating new cross-sell and platform-integration tests.",
    sourceName: "EcoOnline announcement",
    sourceUrl: "https://www.ecoonline.com/en-au/news/ecoonline-announces-d4h-acquisition/",
    sourceTier: "Official company",
  },
  {
    id: "ideagen-beakon-2025",
    announcedAt: "2025-02-03",
    company: "Ideagen",
    counterparty: "Beakon",
    type: "Acquisition",
    status: "Closed",
    domain: "Contractor Management",
    geography: "Asia-Pacific + global",
    headline: "Ideagen acquires Beakon",
    fact: "Ideagen acquired Beakon, an Australian EHS and contractor-management SaaS provider with permit-to-work, qualification, and site-visitor workflows.",
    strategicThesis: "Build contractor and transient-workforce compliance depth while expanding the Asia-Pacific footprint.",
    boardImplication: "Ideagen is assembling both broad EHS and contractor-specific workflows, increasing overlap with specialist contractor platforms.",
    sourceName: "Ideagen announcement",
    sourceUrl: "https://www.ideagen.com/company/news/ideagen-acquires-beakon-to-strengthen-safety-and-compliance",
    sourceTier: "Official company",
  },
  {
    id: "cority-meddbase-2025",
    announcedAt: "2025-01-23",
    company: "Cority",
    counterparty: "Meddbase",
    type: "Acquisition",
    status: "Closed",
    domain: "Occupational Health",
    geography: "North America + Europe + Australia",
    headline: "Cority acquires Meddbase",
    fact: "Cority acquired Meddbase, a cloud-native occupational medicine and enterprise medical-practice platform, for its Health Cloud.",
    strategicThesis: "Deepen clinical and occupational-health workflows and expand geographic coverage.",
    boardImplication: "Occupational health remains a differentiated enterprise wedge and a route into healthcare-provider workflows beyond traditional EHS buyers.",
    sourceName: "Cority announcement",
    sourceUrl: "https://www.cority.com/news-media/cority-acquires-occupational-health-software-meddbase/",
    sourceTier: "Official company",
  },
  {
    id: "safetyculture-funding-2024",
    announcedAt: "2024-09-09",
    company: "SafetyCulture",
    counterparty: "AirTree-led investor group",
    type: "Investment",
    status: "Closed",
    domain: "Core EHS",
    geography: "Global",
    headline: "SafetyCulture closes a $165 million funding round",
    fact: "SafetyCulture reported closing a $165 million funding round and later linked the capital position to its continuing platform expansion and leadership transition.",
    strategicThesis: "Fund continued evolution from inspection-led safety tooling toward a broader operations platform.",
    boardImplication: "The company has substantial capital capacity to invest in product breadth, global distribution, and acquisitions; the operative question is execution rather than access to capital.",
    sourceName: "SafetyCulture leadership announcement",
    sourceUrl: "https://blog.safetyculture.com/media-release/kelly-vohs-appointed-as-ceo-of-safetyculture-luke-anear-to-become-executive-chairman",
    sourceTier: "Official company",
  },
  {
    id: "amcs-eqt-2024",
    announcedAt: "2024-08-14",
    company: "AMCS",
    counterparty: "EQT Private Equity",
    type: "Investment",
    status: "Announced",
    domain: "Sustainability",
    geography: "Global",
    headline: "EQT agrees to acquire a majority stake in AMCS",
    fact: "AMCS and EQT announced that EQT X and EQT Future would acquire a majority stake in AMCS, whose portfolio includes ERP, recycling, transport, EHSQ, and ESG software.",
    strategicThesis: "Back a global performance-sustainability platform serving foundational and circular-economy industries.",
    boardImplication: "Large-cap PE is underwriting convergence across operational software, EHSQ, ESG, and circular-economy workflows—not EHS as an isolated category.",
    sourceName: "AMCS and EQT announcement",
    sourceUrl: "https://www.amcsgroup.com/resources/press-releases/eqt-private-equity-to-acquire-majority-stake-in-amcs/",
    sourceTier: "Official investor",
  },
  {
    id: "workiva-sustainlife-2024",
    announcedAt: "2024-06-17",
    company: "Workiva",
    counterparty: "Sustain.Life",
    type: "Acquisition",
    status: "Closed",
    domain: "Sustainability",
    geography: "Global",
    headline: "Workiva acquires Sustain.Life",
    fact: "Workiva's filing states that it acquired all outstanding equity interests in Sustain.Life on June 17, 2024.",
    strategicThesis: "Add carbon-accounting workflows to an enterprise reporting and assurance platform.",
    boardImplication: "Sustainability software faces adjacency pressure from financial reporting and assurance platforms that already own executive reporting workflows.",
    sourceName: "Workiva Form 10-Q",
    sourceUrl: "https://investor.workiva.com/static-files/a1d5982c-4ebd-429c-b57f-ae28047fcb70",
    sourceTier: "Regulatory filing",
  },
  {
    id: "avetta-eqt-2024",
    announcedAt: "2024-04-02",
    company: "Avetta",
    counterparty: "EQT Private Equity",
    type: "Investment",
    status: "Announced",
    domain: "Contractor Management",
    geography: "Global",
    headline: "EQT agrees to acquire Avetta",
    fact: "EQT announced an agreement to acquire Avetta from Welsh, Carson, Anderson & Stowe, with a stated focus on product development, AI automation, and global expansion.",
    strategicThesis: "Scale a global contractor and supply-chain risk network through product and geographic investment.",
    boardImplication: "Contractor-management network effects continue to attract large sponsors; competitive analysis should track both hiring-client growth and contractor-network quality.",
    sourceName: "EQT announcement",
    sourceUrl: "https://eqtgroup.com/news/eqt-to-acquire-avetta-a-global-leader-in-supply-chain-risk-management-software-2024-04-02",
    sourceTier: "Official investor",
  },
  {
    id: "sphera-supplyshift-2024",
    announcedAt: "2024-01-09",
    company: "Sphera",
    counterparty: "SupplyShift",
    type: "Acquisition",
    status: "Closed",
    domain: "Sustainability",
    geography: "Global",
    headline: "Sphera acquires SupplyShift",
    fact: "Sphera acquired SupplyShift, adding supplier mapping, scoring, traceability, and Scope 3 data collection across a network of more than 100,000 suppliers.",
    strategicThesis: "Connect enterprise sustainability and product data to supplier-level Scope 3 and responsible-sourcing workflows.",
    boardImplication: "Supply-chain sustainability is converging with EHS and product stewardship inside larger operational-risk platforms.",
    sourceName: "Sphera announcement",
    sourceUrl: "https://sphera.com/company/news/sphera-acquires-supplyshift/",
    sourceTier: "Official company",
  },
];
