export const messagingTaxonomy = [
  "AI and automation", "connected platform", "operational risk", "contractor safety", "sustainability and ESG", "compliance automation", "frontline and mobile", "analytics and intelligence", "workforce readiness", "supply-chain risk",
];

export const corporateSourceHierarchy = [
  { level: 1, label: "Primary filing or company release", examples: "SEC EDGAR, investor relations, official newsroom", use: "Transaction facts, dates, parties, consideration, management statements" },
  { level: 2, label: "Government or court record", examples: "FTC, DOJ, state registry, court docket", use: "Regulatory status, challenges, approvals, legal events" },
  { level: 3, label: "Approved trade reporting", examples: "EHS Today and named sector publications", use: "Discovery and sector context; facts traced back to primary sources" },
  { level: 4, label: "Analyst interpretation", examples: "Internal synthesis with named author and timestamp", use: "Implications only; never stored as transaction fact" },
];

export const monitoringJobs = [
  { name: "Competitor product surfaces", coverage: "16 mapped competitors", cadence: "Weekly", method: "Snapshot + semantic diff", status: "Mapped" },
  { name: "Official newsrooms", coverage: "Press releases and company announcements", cadence: "Daily", method: "RSS / sitemap / page monitor", status: "Mapped" },
  { name: "SEC EDGAR", coverage: "Public-company filings and exhibits", cadence: "Daily", method: "Official submissions and filing APIs", status: "Ready" },
  { name: "EHS Today watch", coverage: "Sector transactions and product news", cadence: "Daily", method: "Discovery monitor; primary-source confirmation required", status: "Mapped" },
];

export const changeContract = ["company_id", "page_url", "page_type", "captured_at", "content_hash", "previous_hash", "changed_terms", "messaging_tags", "source_excerpt", "review_status"];

export type CorporateEvent = {
  id: string;
  announcedAt: string;
  company: string;
  counterparty: string;
  type: "Acquisition" | "Investment" | "Separation" | "Rebrand" | "Divestiture" | "Integration" | "Merger";
  status: "Announced" | "Closed" | "Operating transition" | "Rebranded" | "Standalone" | "Integrated";
  domain: "Core EHS" | "Contractor Management" | "Sustainability" | "Occupational Health" | "Chemical & Product Compliance" | "Environmental Intelligence" | "Crisis Readiness";
  geography: string;
  headline: string;
  fact: string;
  strategicThesis: string;
  boardImplication: string;
  sourceName: string;
  sourceUrl: string;
  sourceTier: "Official company" | "Official investor" | "Regulatory filing";
  formerName?: string;
  currentIdentity?: string;
  owner?: string;
  integrationState?: "Brand retained" | "Absorbed" | "Standalone" | "Integration pending" | "Unified platform";
  signalTags?: string[];
};

export const corporateEvents: CorporateEvent[] = [
  {
    id: "novara-ensogo-2026",
    announcedAt: "2026-06-09",
    company: "Novara",
    counterparty: "Ensogo",
    type: "Acquisition",
    status: "Closed",
    domain: "Sustainability",
    geography: "North America + international",
    headline: "Novara acquires Ensogo",
    fact: "Novara announced the acquisition of Ensogo, an AI-native sustainability platform, expanding its AI capabilities, sustainability offering, and international footprint.",
    strategicThesis: "Connect operational risk and sustainability data inside a focused high-risk-industry platform.",
    boardImplication: "Novara is extending beyond core safety workflows while retaining a high-risk-industry focus; integration evidence should now be monitored at the module and customer level.",
    sourceName: "Novara announcement",
    sourceUrl: "https://novara.com/blog/novara-acquires-ensogo-to-accelerate-ai-powered-operational-risk-management-and-sustainability-strategy/",
    sourceTier: "Official company",
  },
  {
    id: "novara-separation-2026",
    announcedAt: "2026-01-27",
    company: "Novara",
    counterparty: "KPA",
    type: "Separation",
    status: "Operating transition",
    domain: "Core EHS",
    geography: "North America",
    headline: "KPA separates Novara as an independent company",
    fact: "KPA separated its Flex and Risk Management Center software businesses into Novara, with KPA retaining its automotive focus and Novara serving high-risk industries.",
    strategicThesis: "Create sharper product, capital-allocation, and go-to-market focus around non-automotive operational risk.",
    boardImplication: "The relevant competitive entity is now Novara—not legacy KPA—when evaluating construction, manufacturing, utilities, and oil and gas.",
    sourceName: "Novara announcement",
    sourceUrl: "https://novara.com/blog/kpa-separates-businesses-launching-novara-to-serve-high-risk-industries/",
    sourceTier: "Official company",
  },
  {
    id: "enhesa-totalsds-2025",
    announcedAt: "2025-10-27",
    company: "Enhesa",
    counterparty: "TotalSDS",
    type: "Acquisition",
    status: "Closed",
    domain: "Chemical & Product Compliance",
    geography: "Global",
    headline: "Enhesa acquires TotalSDS",
    fact: "Enhesa acquired TotalSDS to connect regulatory intelligence, chemical hazard information, and SDS authoring and management workflows.",
    strategicThesis: "Move from regulatory intelligence into an end-to-end chemical-compliance operating workflow.",
    boardImplication: "Regulatory-content providers are moving downstream into execution software, increasing pressure on standalone SDS and product-stewardship tools.",
    sourceName: "Enhesa announcement",
    sourceUrl: "https://www.enhesa.com/resources/press/enhesa-acquires-totalsds/",
    sourceTier: "Official company",
  },
  {
    id: "veriforce-highwire-2025",
    announcedAt: "2025-10-22",
    company: "Veriforce",
    counterparty: "Highwire",
    type: "Acquisition",
    status: "Closed",
    domain: "Contractor Management",
    geography: "Global + U.S. construction",
    headline: "Veriforce acquires Highwire",
    fact: "Veriforce acquired Highwire, combining its global contractor network with Highwire's construction-focused prequalification, financial-risk, and field-safety capabilities.",
    strategicThesis: "Add capital-project and construction depth to a global contractor-management network.",
    boardImplication: "Contractor management is consolidating around network scale plus differentiated risk data, with data centers and advanced manufacturing named as expansion environments.",
    sourceName: "Veriforce announcement",
    sourceUrl: "https://veriforce.com/company/press-room/veriforce-acquires-highwire-expanding-leadership-in-contractor-risk-management",
    sourceTier: "Official company",
  },
  {
    id: "ideagen-safetystratus-2025",
    announcedAt: "2025-10-02",
    company: "Ideagen",
    counterparty: "SafetyStratus",
    type: "Acquisition",
    status: "Closed",
    domain: "Chemical & Product Compliance",
    geography: "Global",
    headline: "Ideagen acquires SafetyStratus",
    fact: "Ideagen acquired SafetyStratus to add specialized chemical inventory, radiation, hazardous-waste, and biosafety capabilities to its EHS portfolio.",
    strategicThesis: "Acquire specialized domain depth that broad EHS suites often lack.",
    boardImplication: "Ideagen is using targeted acquisitions to deepen regulated-industry workflows rather than relying only on horizontal platform breadth.",
    sourceName: "Ideagen announcement",
    sourceUrl: "https://www.ideagen.com/company/news/ideagen-acquires-safetystratus-adding-specialized-chemical-management-to-its-ehs-portfolio",
    sourceTier: "Official company",
  },
  {
    id: "ideagen-envirosuite-2025",
    announcedAt: "2025-08-22",
    company: "Ideagen",
    counterparty: "Envirosuite",
    type: "Acquisition",
    status: "Closed",
    domain: "Environmental Intelligence",
    geography: "Global",
    headline: "Ideagen completes Envirosuite acquisition",
    fact: "Ideagen completed the acquisition of Envirosuite, adding real-time monitoring and predictive analytics for noise, air, water, odour, vibration, and community impact.",
    strategicThesis: "Strengthen the environmental side of EHS with sensor-linked operational intelligence.",
    boardImplication: "Environmental monitoring is moving closer to core EHS suites, expanding the competitive surface into industrial IoT and predictive environmental risk.",
    sourceName: "Ideagen completion announcement",
    sourceUrl: "https://www.ideagen.com/company/news/ideagen-completes-acquisition-of-environmental--intelligence-company-envirosuite",
    sourceTier: "Official company",
  },
  {
    id: "ideagen-reactec-2025",
    announcedAt: "2025-08-18",
    company: "Ideagen",
    counterparty: "Reactec",
    type: "Acquisition",
    status: "Closed",
    domain: "Core EHS",
    geography: "Global",
    headline: "Ideagen acquires Reactec",
    fact: "Ideagen acquired Reactec, adding wearables and analytics for vibration, dust, noise, and proximity hazards in high-risk industries.",
    strategicThesis: "Link worker exposure data and proactive hazard sensing to established EHS workflows.",
    boardImplication: "Connected-worker and exposure-monitoring capabilities are becoming an acquisition path into predictive safety.",
    sourceName: "Ideagen announcement",
    sourceUrl: "https://www.ideagen.com/company/news/ideagen-expands-safety-solutions-with-reactec-acquisition",
    sourceTier: "Official company",
  },
  {
    id: "ecoonline-d4h-2025",
    announcedAt: "2025-06-24",
    company: "EcoOnline",
    counterparty: "D4H",
    type: "Acquisition",
    status: "Closed",
    domain: "Crisis Readiness",
    geography: "Global",
    headline: "EcoOnline acquires D4H",
    fact: "EcoOnline acquired D4H to add crisis-readiness and response software connected to its EHS, chemical-safety, and sustainability products.",
    strategicThesis: "Extend prevention and compliance workflows into real-time crisis coordination and resilience.",
    boardImplication: "The EHS suite boundary is expanding into business continuity and emergency operations, creating new cross-sell and platform-integration tests.",
    sourceName: "EcoOnline announcement",
    sourceUrl: "https://www.ecoonline.com/en-au/news/ecoonline-announces-d4h-acquisition/",
    sourceTier: "Official company",
  },
  {
    id: "ideagen-beakon-2025",
    announcedAt: "2025-02-03",
    company: "Ideagen",
    counterparty: "Beakon",
    type: "Acquisition",
    status: "Closed",
    domain: "Contractor Management",
    geography: "Asia-Pacific + global",
    headline: "Ideagen acquires Beakon",
    fact: "Ideagen acquired Beakon, an Australian EHS and contractor-management SaaS provider with permit-to-work, qualification, and site-visitor workflows.",
    strategicThesis: "Build contractor and transient-workforce compliance depth while expanding the Asia-Pacific footprint.",
    boardImplication: "Ideagen is assembling both broad EHS and contractor-specific workflows, increasing overlap with specialist contractor platforms.",
    sourceName: "Ideagen announcement",
    sourceUrl: "https://www.ideagen.com/company/news/ideagen-acquires-beakon-to-strengthen-safety-and-compliance",
    sourceTier: "Official company",
  },
  {
    id: "cority-meddbase-2025",
    announcedAt: "2025-01-23",
    company: "Cority",
    counterparty: "Meddbase",
    type: "Acquisition",
    status: "Closed",
    domain: "Occupational Health",
    geography: "North America + Europe + Australia",
    headline: "Cority acquires Meddbase",
    fact: "Cority acquired Meddbase, a cloud-native occupational medicine and enterprise medical-practice platform, for its Health Cloud.",
    strategicThesis: "Deepen clinical and occupational-health workflows and expand geographic coverage.",
    boardImplication: "Occupational health remains a differentiated enterprise wedge and a route into healthcare-provider workflows beyond traditional EHS buyers.",
    sourceName: "Cority announcement",
    sourceUrl: "https://www.cority.com/news-media/cority-acquires-occupational-health-software-meddbase/",
    sourceTier: "Official company",
  },
  {
    id: "safetyculture-funding-2024",
    announcedAt: "2024-09-09",
    company: "SafetyCulture",
    counterparty: "AirTree-led investor group",
    type: "Investment",
    status: "Closed",
    domain: "Core EHS",
    geography: "Global",
    headline: "SafetyCulture closes a $165 million funding round",
    fact: "SafetyCulture reported closing a $165 million funding round and later linked the capital position to its continuing platform expansion and leadership transition.",
    strategicThesis: "Fund continued evolution from inspection-led safety tooling toward a broader operations platform.",
    boardImplication: "The company has substantial capital capacity to invest in product breadth, global distribution, and acquisitions; the operative question is execution rather than access to capital.",
    sourceName: "SafetyCulture leadership announcement",
    sourceUrl: "https://blog.safetyculture.com/media-release/kelly-vohs-appointed-as-ceo-of-safetyculture-luke-anear-to-become-executive-chairman",
    sourceTier: "Official company",
  },
  {
    id: "amcs-eqt-2024",
    announcedAt: "2024-08-14",
    company: "AMCS",
    counterparty: "EQT Private Equity",
    type: "Investment",
    status: "Announced",
    domain: "Sustainability",
    geography: "Global",
    headline: "EQT agrees to acquire a majority stake in AMCS",
    fact: "AMCS and EQT announced that EQT X and EQT Future would acquire a majority stake in AMCS, whose portfolio includes ERP, recycling, transport, EHSQ, and ESG software.",
    strategicThesis: "Back a global performance-sustainability platform serving foundational and circular-economy industries.",
    boardImplication: "Large-cap PE is underwriting convergence across operational software, EHSQ, ESG, and circular-economy workflows—not EHS as an isolated category.",
    sourceName: "AMCS and EQT announcement",
    sourceUrl: "https://www.amcsgroup.com/resources/press-releases/eqt-private-equity-to-acquire-majority-stake-in-amcs/",
    sourceTier: "Official investor",
  },
  {
    id: "workiva-sustainlife-2024",
    announcedAt: "2024-06-17",
    company: "Workiva",
    counterparty: "Sustain.Life",
    type: "Acquisition",
    status: "Closed",
    domain: "Sustainability",
    geography: "Global",
    headline: "Workiva acquires Sustain.Life",
    fact: "Workiva's filing states that it acquired all outstanding equity interests in Sustain.Life on June 17, 2024.",
    strategicThesis: "Add carbon-accounting workflows to an enterprise reporting and assurance platform.",
    boardImplication: "Sustainability software faces adjacency pressure from financial reporting and assurance platforms that already own executive reporting workflows.",
    sourceName: "Workiva Form 10-Q",
    sourceUrl: "https://investor.workiva.com/static-files/a1d5982c-4ebd-429c-b57f-ae28047fcb70",
    sourceTier: "Regulatory filing",
  },
  {
    id: "avetta-eqt-2024",
    announcedAt: "2024-04-02",
    company: "Avetta",
    counterparty: "EQT Private Equity",
    type: "Investment",
    status: "Announced",
    domain: "Contractor Management",
    geography: "Global",
    headline: "EQT agrees to acquire Avetta",
    fact: "EQT announced an agreement to acquire Avetta from Welsh, Carson, Anderson & Stowe, with a stated focus on product development, AI automation, and global expansion.",
    strategicThesis: "Scale a global contractor and supply-chain risk network through product and geographic investment.",
    boardImplication: "Contractor-management network effects continue to attract large sponsors; competitive analysis should track both hiring-client growth and contractor-network quality.",
    sourceName: "EQT announcement",
    sourceUrl: "https://eqtgroup.com/news/eqt-to-acquire-avetta-a-global-leader-in-supply-chain-risk-management-software-2024-04-02",
    sourceTier: "Official investor",
  },
  {
    id: "sphera-supplyshift-2024",
    announcedAt: "2024-01-09",
    company: "Sphera",
    counterparty: "SupplyShift",
    type: "Acquisition",
    status: "Closed",
    domain: "Sustainability",
    geography: "Global",
    headline: "Sphera acquires SupplyShift",
    fact: "Sphera acquired SupplyShift, adding supplier mapping, scoring, traceability, and Scope 3 data collection across a network of more than 100,000 suppliers.",
    strategicThesis: "Connect enterprise sustainability and product data to supplier-level Scope 3 and responsible-sourcing workflows.",
    boardImplication: "Supply-chain sustainability is converging with EHS and product stewardship inside larger operational-risk platforms.",
    sourceName: "Sphera announcement",
    sourceUrl: "https://sphera.com/company/news/sphera-acquires-supplyshift/",
    sourceTier: "Official company",
  },
  {
    id: "mitti-rebrand-2026",
    announcedAt: "2026-08-11",
    company: "Mitti",
    counterparty: "SafetyCulture",
    type: "Rebrand",
    status: "Rebranded",
    domain: "Core EHS",
    geography: "Global",
    headline: "SafetyCulture becomes Mitti",
    fact: "SafetyCulture adopted the Mitti name and repositioned the company around an integrated frontline-operations platform spanning software, hardware, consumables, insurance, and AI.",
    strategicThesis: "Expand the category from safety software into a broader operating system for frontline work.",
    boardImplication: "Competitive tracking must follow the Mitti identity and test whether the broader platform creates meaningful cross-product adoption beyond the legacy inspection franchise.",
    sourceName: "Mitti announcement",
    sourceUrl: "https://mitti.com/media-releases/safetyculture-becomes-mitti-unveiling-a-platform-built-for-the-future-of-frontline-work",
    sourceTier: "Official company",
    formerName: "SafetyCulture",
    currentIdentity: "Mitti",
    integrationState: "Unified platform",
    signalTags: ["name change", "category expansion", "frontline operations", "AI"],
  },
  {
    id: "pureehs-carveout-2026",
    announcedAt: "2026-04-02",
    company: "Peak Rock Capital",
    counterparty: "UL Solutions EHS software business",
    type: "Divestiture",
    status: "Standalone",
    domain: "Occupational Health",
    geography: "North America",
    headline: "UL Solutions EHS software becomes PureEHS",
    fact: "Peak Rock completed its acquisition of UL Solutions' Employee Health and Safety software business and launched PureEHS as a standalone company combining PureOHS, OHM, SYSTOC, and LearnShare.",
    strategicThesis: "Create a focused EHS, occupational-health, clinical, and training platform from a corporate carve-out.",
    boardImplication: "PureEHS is a newly independent competitor with sponsor-backed capacity and an installed base; product investment and customer retention are the immediate diligence questions.",
    sourceName: "Peak Rock announcement",
    sourceUrl: "https://www.peakrockcapital.com/images/news/pdf/Peak%20Rock%20Capital%20affiliate%20completes%20acquisition%20of%20the%20Employee%20Health%20and%20Safety%20software%20business%20of%20UL%20Solutions.pdf",
    sourceTier: "Official investor",
    formerName: "UL Solutions EHS software business",
    currentIdentity: "PureEHS",
    owner: "Peak Rock Capital",
    integrationState: "Standalone",
    signalTags: ["carve-out", "new competitor", "occupational health", "training"],
  },
  {
    id: "safetyculture-twine-2026",
    announcedAt: "2026-04-07",
    company: "SafetyCulture",
    counterparty: "Twine team",
    type: "Acquisition",
    status: "Closed",
    domain: "Core EHS",
    geography: "Global",
    headline: "SafetyCulture acquires Twine team",
    fact: "SafetyCulture acquired the Twine team to accelerate its agentic platform ambitions and AI product development.",
    strategicThesis: "Acquire specialized AI talent rather than a standalone workflow product.",
    boardImplication: "This is a capability acquisition; evidence should be sought in shipped agents, workflow automation, and measurable product adoption—not announcement language alone.",
    sourceName: "Mitti announcement",
    sourceUrl: "https://mitti.com/media-releases/safetyculture-acquires-twine-to-accelerate-agentic-platform-ambitions",
    sourceTier: "Official company",
    integrationState: "Absorbed",
    signalTags: ["acqui-hire", "agentic AI", "product acceleration"],
  },
  {
    id: "alcumus-veriforce-merger-2025",
    announcedAt: "2025-06-30",
    company: "Veriforce",
    counterparty: "Alcumus",
    type: "Merger",
    status: "Operating transition",
    domain: "Contractor Management",
    geography: "Global",
    headline: "Alcumus merges with Veriforce",
    fact: "Apax reports that Alcumus merged with Veriforce in 2025, joining large contractor, supplier, certification, and safety networks under common ownership.",
    strategicThesis: "Combine network scale, contractor qualification, supply-chain assurance, and EHS services across regions.",
    boardImplication: "The resulting network is strategically important, but brand, product, and customer migration should be tracked separately from sponsor claims about scale.",
    sourceName: "Apax portfolio record",
    sourceUrl: "https://www.apax.com/partnerships/alcumus/",
    sourceTier: "Official investor",
    owner: "Apax Partners",
    integrationState: "Integration pending",
    signalTags: ["network consolidation", "contractor management", "supplier risk"],
  },
  {
    id: "evotix-divestiture-2024",
    announcedAt: "2024-10-23",
    company: "Evotix",
    counterparty: "SAI360",
    type: "Divestiture",
    status: "Standalone",
    domain: "Core EHS",
    geography: "Global",
    headline: "Evotix becomes standalone after SAI360 divestiture",
    fact: "SAI360 completed the divestiture of its EHS&S business to Evotix, which became a standalone company in Symphony Technology Group's portfolio and launched a refreshed identity.",
    strategicThesis: "Restore a singular EHS&S operating focus under a dedicated brand and sponsor structure.",
    boardImplication: "Evotix should be evaluated as an independent platform, with renewed attention to investment pace, packaging, AI delivery, and enterprise retention.",
    sourceName: "Evotix announcement",
    sourceUrl: "https://www.evotix.com/news-and-press/evotix-concludes-divestiture-from-sai360-with-unified-brand-identity",
    sourceTier: "Official company",
    formerName: "SAI360 EHS&S business",
    currentIdentity: "Evotix",
    owner: "Symphony Technology Group",
    integrationState: "Standalone",
    signalTags: ["divestiture", "standalone", "brand refresh"],
  },
  {
    id: "sphera-scrm-integration-2024",
    announcedAt: "2024-06-03",
    company: "Sphera",
    counterparty: "riskmethods + SupplyShift",
    type: "Integration",
    status: "Integrated",
    domain: "Sustainability",
    geography: "Global",
    headline: "riskmethods and SupplyShift become Sphera SCRM",
    fact: "Sphera brought the riskmethods and SupplyShift capabilities together under the Sphera Supply Chain Risk Management identity.",
    strategicThesis: "Unify supplier risk, mapping, sustainability, and responsible-sourcing capabilities into one market-facing platform.",
    boardImplication: "This is stronger integration evidence than an acquisition announcement because the products are being presented through a shared solution identity.",
    sourceName: "Sphera integration page",
    sourceUrl: "https://sphera.com/riskmethods-supplyshift-are-now-sphera-scrm/",
    sourceTier: "Official company",
    formerName: "riskmethods + SupplyShift",
    currentIdentity: "Sphera SCRM",
    owner: "Blackstone",
    integrationState: "Unified platform",
    signalTags: ["product integration", "supply-chain risk", "brand absorption"],
  },
];

export type BrandLineage = {
  id: string;
  from: string;
  to: string;
  effective: string;
  transition: string;
  state: "Rebranded" | "Standalone" | "Absorbed" | "Unified";
  sourceUrl: string;
};

export const brandLineages: BrandLineage[] = [
  { id: "safetyculture-mitti", from: "SafetyCulture", to: "Mitti", effective: "Aug 2026", transition: "Company-wide rebrand and category expansion", state: "Rebranded", sourceUrl: "https://mitti.com/media-releases/safetyculture-becomes-mitti-unveiling-a-platform-built-for-the-future-of-frontline-work" },
  { id: "kpa-novara", from: "KPA Flex + Risk Management Center", to: "Novara", effective: "Jan 2026", transition: "Software businesses separated from automotive-focused KPA", state: "Standalone", sourceUrl: "https://novara.com/blog/kpa-separates-businesses-launching-novara-to-serve-high-risk-industries/" },
  { id: "ul-pureehs", from: "UL Solutions EHS software", to: "PureEHS", effective: "Apr 2026", transition: "Sponsor-backed carve-out retaining four product lines", state: "Standalone", sourceUrl: "https://www.peakrockcapital.com/images/news/pdf/Peak%20Rock%20Capital%20affiliate%20completes%20acquisition%20of%20the%20Employee%20Health%20and%20Safety%20software%20business%20of%20UL%20Solutions.pdf" },
  { id: "sai-evotix", from: "SAI360 EHS&S", to: "Evotix", effective: "Oct 2024", transition: "Divestiture and refreshed standalone identity", state: "Standalone", sourceUrl: "https://www.evotix.com/news-and-press/evotix-concludes-divestiture-from-sai360-with-unified-brand-identity" },
  { id: "constructsecure-highwire", from: "ConstructSecure", to: "Highwire → Veriforce", effective: "2022–2025", transition: "Rebrand followed by acquisition into contractor network", state: "Absorbed", sourceUrl: "https://veriforce.com/company/press-room/veriforce-acquires-highwire-expanding-leadership-in-contractor-risk-management" },
  { id: "processmap-ideagen", from: "ProcessMAP", to: "Ideagen EHS", effective: "2022–present", transition: "EHS platform combined into Ideagen portfolio", state: "Absorbed", sourceUrl: "https://www.ideagen.com/company/news/ideagen-and-processmap-to-combine-their-strengths-to-create-a-world-leading-health-and-safety-software-solution" },
  { id: "riskmethods-sphera", from: "riskmethods + SupplyShift", to: "Sphera SCRM", effective: "2024", transition: "Acquired capabilities unified into one SCRM solution", state: "Unified", sourceUrl: "https://sphera.com/riskmethods-supplyshift-are-now-sphera-scrm/" },
  { id: "medgate-cority", from: "Medgate", to: "Cority", effective: "2017–present", transition: "Corporate rebrand retained as current EHS platform identity", state: "Rebranded", sourceUrl: "https://www.cority.com/news-media/medgate-rebrands-as-cority/" },
];

export type OwnershipGroup = {
  sponsor: string;
  platforms: string[];
  relationship: string;
  watch: string;
  sourceUrl: string;
};

export const ownershipGroups: OwnershipGroup[] = [
  { sponsor: "Apax Partners", platforms: ["Veriforce", "Alcumus"], relationship: "Merged operating network", watch: "Brand convergence, network interoperability, geographic cross-sell", sourceUrl: "https://www.apax.com/partnerships/alcumus/" },
  { sponsor: "Hg", platforms: ["Ideagen"], relationship: "Growth partnership", watch: "Acquisition cadence, EHS specialization, integration of acquired products", sourceUrl: "https://www.ideagen.com/company/news/ideagen-secures-partnership-with-hg-to-support-further-growth-as-a-regulatory-and-compliance-software-leader" },
  { sponsor: "Blackstone", platforms: ["Sphera"], relationship: "Control investment", watch: "EHS, ESG, product stewardship, and supply-chain platform convergence", sourceUrl: "https://sphera.com/company/news/blackstone-to-acquire-sphera/" },
  { sponsor: "EQT", platforms: ["Avetta", "AMCS"], relationship: "Separate portfolio companies", watch: "Do not infer integration; monitor adjacent contractor, ESG, and industrial software theses", sourceUrl: "https://eqtgroup.com/news/eqt-to-acquire-avetta-a-global-leader-in-supply-chain-risk-management-software-2024-04-02" },
  { sponsor: "Peak Rock Capital", platforms: ["PureEHS"], relationship: "Corporate carve-out", watch: "Customer retention, independent roadmap, AI investment, add-on acquisitions", sourceUrl: "https://www.peakrockcapital.com/images/news/pdf/Peak%20Rock%20Capital%20affiliate%20completes%20acquisition%20of%20the%20Employee%20Health%20and%20Safety%20software%20business%20of%20UL%20Solutions.pdf" },
  { sponsor: "Symphony Technology Group", platforms: ["Evotix"], relationship: "Standalone portfolio company", watch: "Operating investment after SAI360 divestiture", sourceUrl: "https://www.evotix.com/news-and-press/evotix-concludes-divestiture-from-sai360-with-unified-brand-identity" },
];

export const corporateWorkflows = [
  { name: "Deal and identity monitor", cadence: "Daily", coverage: "Newsrooms, sponsor portfolios, filings, acquired-company redirects", process: "Discover → resolve aliases → verify primary source → classify event", output: "Verified event + lineage update", status: "Research mapped" },
  { name: "Transaction lifecycle tracker", cadence: "Weekly", coverage: "Announced, closed, separated, integrated, sunsetted", process: "Recheck status → capture product evidence → flag unresolved transitions", output: "Lifecycle and integration state", status: "Research mapped" },
  { name: "Ownership and roll-up map", cadence: "Monthly", coverage: "Sponsors, operating companies, add-ons, shared ownership", process: "Confirm sponsor page → separate ownership from operational integration", output: "Board-ready ownership map", status: "Research mapped" },
  { name: "Product absorption monitor", cadence: "Weekly", coverage: "Navigation, packaging, product names, redirects, release notes", process: "Snapshot surfaces → compare names/modules → require observable evidence", output: "Retained, absorbed, unified, or pending", status: "Research mapped" },
  { name: "Executive diligence brief", cadence: "On demand", coverage: "Selected company, sponsor, domain, and time window", process: "Assemble facts → isolate inference → surface open diligence questions", output: "Exportable one-page brief", status: "Designed" },
];
