export type MarketSegment = {
  id: string;
  vertical: string;
  segment: string;
  naics: string[];
  geographies: string[];
  workforce: string[];
  agencies: string[];
  obligations: string[];
  operationalExposure: string[];
  productWorkflows: string[];
};

export const marketSegments: MarketSegment[] = [
  {
    id: "construction-commercial",
    vertical: "Construction",
    segment: "Commercial & institutional construction",
    naics: ["236220"],
    geographies: ["United States", "State", "Metro"],
    workforce: ["General contractors", "Subcontractors", "Temporary labor"],
    agencies: ["OSHA", "State OSHA Plans", "State environmental agencies"],
    obligations: ["Jobsite safety", "Training", "Recordkeeping", "Hazard communication"],
    operationalExposure: ["Multi-employer worksites", "Falls", "Heat", "Mobile equipment"],
    productWorkflows: ["Incident Management", "Training", "Contractor Management", "Mobile Forms"],
  },
  {
    id: "construction-infrastructure",
    vertical: "Construction",
    segment: "Heavy civil & infrastructure",
    naics: ["237310", "237990"],
    geographies: ["United States", "State", "Project corridor"],
    workforce: ["Prime contractors", "Specialty trades", "Public-sector contractors"],
    agencies: ["OSHA", "State OSHA Plans", "DOT", "EPA"],
    obligations: ["Jobsite safety", "Environmental permits", "Contractor qualification", "Equipment inspection"],
    operationalExposure: ["Traffic zones", "Excavation", "Heavy equipment", "Distributed crews"],
    productWorkflows: ["Contractor Management", "Asset Management", "Incident Management", "Training"],
  },
  {
    id: "construction-data-centers",
    vertical: "Construction",
    segment: "Data center construction",
    naics: ["236220"],
    geographies: ["United States", "State", "Metro", "Project site"],
    workforce: ["General contractors", "Electrical trades", "Mechanical trades", "Commissioning teams"],
    agencies: ["OSHA", "State OSHA Plans", "Local fire authorities", "EPA"],
    obligations: ["Multi-employer coordination", "Electrical safety", "Training", "Environmental controls"],
    operationalExposure: ["Rapid project scaling", "Energization", "Contractor density", "Schedule pressure"],
    productWorkflows: ["Contractor Management", "Training", "Incident Management", "Mobile Forms"],
  },
  {
    id: "construction-industrial",
    vertical: "Construction",
    segment: "Industrial building construction",
    naics: ["236210"],
    geographies: ["United States", "State", "Metro", "Project site"],
    workforce: ["General contractors", "Mechanical trades", "Electrical trades", "Commissioning teams"],
    agencies: ["OSHA", "State OSHA Plans", "EPA", "Local fire authorities"],
    obligations: ["Multi-employer coordination", "Process-area safety", "Environmental controls", "Commissioning safety"],
    operationalExposure: ["Heavy lifts", "Energization", "Hot work", "Schedule compression"],
    productWorkflows: ["Contractor Management", "Permit to Work", "Training", "Incident Management"],
  },
  {
    id: "construction-concrete",
    vertical: "Construction",
    segment: "Poured concrete structure construction",
    naics: ["238110"],
    geographies: ["United States", "State", "Metro", "Project site"],
    workforce: ["Concrete contractors", "Pump operators", "Finishers", "Laborers"],
    agencies: ["OSHA", "State OSHA Plans", "DOT"],
    obligations: ["Fall protection", "Silica control", "Equipment inspection", "Training"],
    operationalExposure: ["Formwork", "Concrete pumping", "Silica", "Struck-by hazards"],
    productWorkflows: ["Training", "Inspections", "Incident Management", "Mobile Forms"],
  },
  {
    id: "construction-electrical",
    vertical: "Construction",
    segment: "Electrical contractors",
    naics: ["238210"],
    geographies: ["United States", "State", "Metro", "Project site"],
    workforce: ["Electricians", "Low-voltage technicians", "Apprentices", "Commissioning crews"],
    agencies: ["OSHA", "State OSHA Plans", "Local electrical authorities"],
    obligations: ["Electrical safety", "Lockout/tagout", "Training", "Equipment inspection"],
    operationalExposure: ["Arc flash", "Energized work", "Ladders", "Temporary power"],
    productWorkflows: ["Training", "Permit to Work", "Inspections", "Incident Management"],
  },
  {
    id: "construction-roofing",
    vertical: "Construction",
    segment: "Roofing contractors",
    naics: ["238160"],
    geographies: ["United States", "State", "Metro", "Project site"],
    workforce: ["Roofers", "Laborers", "Subcontractors"],
    agencies: ["OSHA", "State OSHA Plans"],
    obligations: ["Fall protection", "Heat prevention", "Training", "Recordkeeping"],
    operationalExposure: ["Falls", "Heat", "Weather", "Material handling"],
    productWorkflows: ["Training", "Inspections", "Incident Management", "Mobile Forms"],
  },
  {
    id: "manufacturing-durable",
    vertical: "Manufacturing",
    segment: "Durable goods manufacturing",
    naics: ["332", "333", "336"],
    geographies: ["United States", "State", "Plant"],
    workforce: ["Production employees", "Maintenance", "Material handling", "Contractors"],
    agencies: ["OSHA", "EPA", "State environmental agencies"],
    obligations: ["Machine safety", "Hazard communication", "Air and waste compliance", "Recordkeeping"],
    operationalExposure: ["Machine guarding", "Lockout/tagout", "Ergonomics", "Chemical use"],
    productWorkflows: ["Incident Management", "Asset Management", "SDS Management", "Training"],
  },
  {
    id: "manufacturing-chemicals",
    vertical: "Manufacturing",
    segment: "Chemical manufacturing",
    naics: ["325"],
    geographies: ["United States", "State", "Facility", "Watershed"],
    workforce: ["Operators", "Maintenance", "Laboratory", "Emergency response"],
    agencies: ["OSHA", "EPA", "State environmental agencies", "DHS"],
    obligations: ["Process safety", "Hazard communication", "Air", "Water", "Hazardous waste"],
    operationalExposure: ["Process hazards", "Chemical releases", "Turnarounds", "Emergency response"],
    productWorkflows: ["SDS Management", "Incident Management", "Training", "Asset Management"],
  },
  {
    id: "manufacturing-food",
    vertical: "Manufacturing",
    segment: "Food manufacturing",
    naics: ["311"],
    geographies: ["United States", "State", "Facility"],
    workforce: ["Production employees", "Sanitation crews", "Maintenance", "Warehouse staff"],
    agencies: ["OSHA", "EPA", "FDA", "USDA"],
    obligations: ["Machine safety", "Chemical safety", "Food safety", "Wastewater compliance"],
    operationalExposure: ["Amputations", "Ergonomics", "Refrigeration", "Wet environments"],
    productWorkflows: ["Incident Management", "Training", "SDS Management", "Inspections"],
  },
  {
    id: "manufacturing-primary-metals",
    vertical: "Manufacturing",
    segment: "Primary metal manufacturing",
    naics: ["331"],
    geographies: ["United States", "State", "Facility"],
    workforce: ["Furnace operators", "Foundry workers", "Maintenance", "Material handling"],
    agencies: ["OSHA", "EPA", "State environmental agencies"],
    obligations: ["Machine safety", "Heat exposure", "Air permits", "Hazardous waste"],
    operationalExposure: ["Molten metal", "Heat", "Heavy equipment", "Air emissions"],
    productWorkflows: ["Incident Management", "Industrial Hygiene", "Training", "Environmental Compliance"],
  },
  {
    id: "manufacturing-semiconductors",
    vertical: "Manufacturing",
    segment: "Semiconductor manufacturing",
    naics: ["334413"],
    geographies: ["United States", "State", "Facility"],
    workforce: ["Fabrication technicians", "Engineers", "Maintenance", "Laboratory staff"],
    agencies: ["OSHA", "EPA", "State environmental agencies"],
    obligations: ["Chemical management", "Air permits", "Emergency response", "Hazard communication"],
    operationalExposure: ["Toxic gases", "Cleanrooms", "Process chemicals", "High-purity systems"],
    productWorkflows: ["SDS Management", "Environmental Compliance", "Training", "Incident Management"],
  },
  {
    id: "manufacturing-refining",
    vertical: "Manufacturing",
    segment: "Petroleum refineries",
    naics: ["324110"],
    geographies: ["United States", "State", "Facility", "Watershed"],
    workforce: ["Process operators", "Maintenance", "Turnaround contractors", "Emergency response"],
    agencies: ["OSHA", "EPA", "State environmental agencies", "DHS"],
    obligations: ["Process safety management", "Risk management planning", "Air permits", "Hazardous waste"],
    operationalExposure: ["Process containment", "Turnarounds", "Hot work", "Contractor concentration"],
    productWorkflows: ["Process Safety", "Contractor Management", "Permit to Work", "Environmental Compliance"],
  },
  {
    id: "energy-oil-gas",
    vertical: "Energy & Utilities",
    segment: "Oil & gas operations",
    naics: ["211", "213111", "213112"],
    geographies: ["United States", "State", "Basin", "Site"],
    workforce: ["Operators", "Service contractors", "Drivers", "Maintenance"],
    agencies: ["OSHA", "EPA", "State oil and gas agencies", "DOT / PHMSA"],
    obligations: ["Worker safety", "Environmental reporting", "Contractor oversight", "Emergency response"],
    operationalExposure: ["Remote worksites", "Driving", "Pressure equipment", "Contractor concentration"],
    productWorkflows: ["Contractor Management", "Incident Management", "Training", "Mobile Forms"],
  },
  {
    id: "energy-oil-extraction",
    vertical: "Energy & Utilities",
    segment: "Crude petroleum extraction",
    naics: ["211120"],
    geographies: ["United States", "State", "Basin", "Site"],
    workforce: ["Lease operators", "Production technicians", "Maintenance", "Service contractors"],
    agencies: ["OSHA", "EPA", "State oil and gas agencies", "BLM"],
    obligations: ["Worker safety", "Spill prevention", "Air emissions", "Well-site reporting"],
    operationalExposure: ["Remote sites", "Pressure equipment", "Driving", "Flammable materials"],
    productWorkflows: ["Contractor Management", "Incident Management", "Environmental Compliance", "Mobile Forms"],
  },
  {
    id: "energy-well-drilling",
    vertical: "Energy & Utilities",
    segment: "Drilling oil and gas wells",
    naics: ["213111"],
    geographies: ["United States", "State", "Basin", "Rig"],
    workforce: ["Drilling crews", "Roustabouts", "Service contractors", "Drivers"],
    agencies: ["OSHA", "State oil and gas agencies", "DOT"],
    obligations: ["Rig safety", "Contractor oversight", "Training", "Emergency response"],
    operationalExposure: ["Rotating equipment", "Pressure", "Falls", "Fatigue"],
    productWorkflows: ["Contractor Management", "Training", "Incident Management", "Inspections"],
  },
  {
    id: "energy-oil-support",
    vertical: "Energy & Utilities",
    segment: "Support activities for oil and gas",
    naics: ["213112"],
    geographies: ["United States", "State", "Basin", "Site"],
    workforce: ["Field service crews", "Well-service contractors", "Drivers", "Equipment operators"],
    agencies: ["OSHA", "State oil and gas agencies", "DOT"],
    obligations: ["Contractor qualification", "Equipment safety", "Training", "Incident reporting"],
    operationalExposure: ["Mobile equipment", "Pressure pumping", "Driving", "Temporary worksites"],
    productWorkflows: ["Contractor Management", "Training", "Asset Management", "Incident Management"],
  },
  {
    id: "energy-renewables",
    vertical: "Energy & Utilities",
    segment: "Renewable power construction & operations",
    naics: ["221114", "221115", "237130"],
    geographies: ["United States", "State", "Project site"],
    workforce: ["Construction crews", "Technicians", "Electrical contractors", "Asset operators"],
    agencies: ["OSHA", "State OSHA Plans", "FERC", "State utility commissions"],
    obligations: ["Electrical safety", "Working at height", "Contractor oversight", "Environmental permits"],
    operationalExposure: ["Remote assets", "Energization", "Weather", "Specialty contractors"],
    productWorkflows: ["Contractor Management", "Asset Management", "Training", "Incident Management"],
  },
  {
    id: "utilities-generation",
    vertical: "Energy & Utilities",
    segment: "Fossil and nuclear electric generation",
    naics: ["221112", "221113"],
    geographies: ["United States", "State", "Plant", "Service territory"],
    workforce: ["Plant operators", "Maintenance", "Outage contractors", "Radiation protection"],
    agencies: ["OSHA", "EPA", "NRC", "FERC", "NERC"],
    obligations: ["Process and electrical safety", "Air and water permits", "Emergency preparedness", "Contractor oversight"],
    operationalExposure: ["High energy systems", "Outages", "Confined spaces", "Hazardous materials"],
    productWorkflows: ["Contractor Management", "Permit to Work", "Asset Management", "Environmental Compliance"],
  },
  {
    id: "utilities-electric",
    vertical: "Energy & Utilities",
    segment: "Electric power transmission & distribution",
    naics: ["221121", "221122"],
    geographies: ["United States", "State", "Service territory"],
    workforce: ["Lineworkers", "Vegetation contractors", "Field service", "Control-room staff"],
    agencies: ["OSHA", "FERC", "NERC", "State utility commissions"],
    obligations: ["Electrical safety", "Reliability", "Contractor oversight", "Emergency preparedness"],
    operationalExposure: ["High voltage", "Storm response", "Distributed workforce", "Public interface"],
    productWorkflows: ["Contractor Management", "Training", "Asset Management", "Incident Management"],
  },
  {
    id: "waste-solid",
    vertical: "Waste & Water",
    segment: "Solid waste collection & disposal",
    naics: ["562111", "562212", "562219"],
    geographies: ["United States", "State", "County", "Facility"],
    workforce: ["Drivers", "Collection crews", "Equipment operators", "Facility staff"],
    agencies: ["OSHA", "EPA", "State environmental agencies", "DOT"],
    obligations: ["Worker safety", "Vehicle safety", "Waste permits", "Environmental monitoring"],
    operationalExposure: ["Transportation", "Heavy equipment", "Public roads", "Hazardous materials"],
    productWorkflows: ["Incident Management", "Asset Management", "Training", "Mobile Forms"],
  },
  {
    id: "waste-hazardous",
    vertical: "Waste & Water",
    segment: "Hazardous waste collection and treatment",
    naics: ["562112", "562211"],
    geographies: ["United States", "State", "Facility", "Route"],
    workforce: ["Drivers", "Treatment operators", "Chemists", "Emergency response"],
    agencies: ["OSHA", "EPA", "DOT", "State environmental agencies"],
    obligations: ["Hazardous waste manifests", "Treatment permits", "Worker protection", "Transportation compliance"],
    operationalExposure: ["Chemical incompatibility", "Transportation", "Fire", "Exposure"],
    productWorkflows: ["SDS Management", "Environmental Compliance", "Training", "Incident Management"],
  },
  {
    id: "waste-remediation",
    vertical: "Waste & Water",
    segment: "Environmental remediation services",
    naics: ["562910"],
    geographies: ["United States", "State", "Project site", "Watershed"],
    workforce: ["Remediation crews", "Environmental technicians", "Equipment operators", "Subcontractors"],
    agencies: ["OSHA", "EPA", "State environmental agencies"],
    obligations: ["Site safety", "Hazardous material handling", "Waste transport", "Environmental monitoring"],
    operationalExposure: ["Unknown contaminants", "Excavation", "Respiratory hazards", "Temporary sites"],
    productWorkflows: ["Contractor Management", "Industrial Hygiene", "Environmental Compliance", "Mobile Forms"],
  },
  {
    id: "waste-material-recovery",
    vertical: "Waste & Water",
    segment: "Materials recovery facilities",
    naics: ["562920"],
    geographies: ["United States", "State", "Facility"],
    workforce: ["Sort-line workers", "Equipment operators", "Drivers", "Maintenance"],
    agencies: ["OSHA", "EPA", "State environmental agencies"],
    obligations: ["Machine safety", "Fire prevention", "Waste permits", "Training"],
    operationalExposure: ["Conveyors", "Mobile equipment", "Lithium batteries", "Airborne contaminants"],
    productWorkflows: ["Incident Management", "Inspections", "Asset Management", "Training"],
  },
  {
    id: "water-utilities",
    vertical: "Waste & Water",
    segment: "Water & wastewater utilities",
    naics: ["221310", "221320"],
    geographies: ["United States", "State", "Service territory", "Watershed"],
    workforce: ["Plant operators", "Field crews", "Laboratory", "Maintenance"],
    agencies: ["EPA", "OSHA", "State drinking water agencies", "State environmental agencies"],
    obligations: ["Water quality", "Discharge permits", "Confined space", "Chemical safety"],
    operationalExposure: ["Confined spaces", "Treatment chemicals", "Distributed assets", "Public health"],
    productWorkflows: ["SDS Management", "Asset Management", "Training", "Incident Management"],
  },
];

export const verticals = Array.from(new Set(marketSegments.map((segment) => segment.vertical)));
