export type SourceDomain = "Injuries" | "Enforcement" | "Economy" | "Regulations" | "Environment" | "Competitors" | "Corporate Activity";

export type SourceDefinition = {
  id: string;
  name: string;
  domain: SourceDomain;
  owner: string;
  authority: "Primary government" | "Official company" | "Approved trade press" | "Internal controlled import";
  transport: "API" | "CSV slices" | "Bulk ZIP" | "Web service" | "RSS / scan" | "File import";
  cadence: string;
  history: string;
  coverage: string;
  url: string;
  status: "Live" | "Ready" | "Mapped" | "Needs credential" | "Needs storage";
  joinKeys: string[];
  caveat: string;
};

export const sourceRegistry: SourceDefinition[] = [
  { id: "osha-ita-summary", name: "OSHA ITA Summary Data", domain: "Injuries", owner: "U.S. OSHA", authority: "Primary government", transport: "Bulk ZIP", cadence: "Annual", history: "2016-present", coverage: "Federal OSHA + State Plans; covered establishments", url: "https://www.osha.gov/itadata", status: "Needs storage", joinKeys: ["establishment_id", "naics", "state", "year"], caveat: "Submitted establishment data is not representative of every U.S. establishment and OSHA does not validate every submitted count." },
  { id: "osha-ita-case", name: "OSHA ITA Case Detail", domain: "Injuries", owner: "U.S. OSHA", authority: "Primary government", transport: "Bulk ZIP", cadence: "Annual", history: "2023-present", coverage: "Covered establishments with 100+ employees in listed industries", url: "https://www.osha.gov/itadata", status: "Needs storage", joinKeys: ["establishment_id", "case_number", "naics", "state", "year"], caveat: "Case detail and summary files have different coverage; establishment_id is the documented linkage key." },
  { id: "osha-sir", name: "OSHA Severe Injury Reports", domain: "Injuries", owner: "U.S. OSHA", authority: "Primary government", transport: "Bulk ZIP", cadence: "Periodic", history: "2015-present", coverage: "Federal OSHA jurisdictions; excludes State Plan incidents", url: "https://www.osha.gov/severeinjury", status: "Needs storage", joinKeys: ["naics", "state", "establishment_name", "event_date", "oics_code"], caveat: "Geocodes vary in precision and the dataset excludes State Plan severe-injury reports." },
  { id: "osha-fatalities", name: "OSHA Fatality Inspection Data", domain: "Injuries", owner: "U.S. OSHA", authority: "Primary government", transport: "RSS / scan", cadence: "Periodic", history: "2017-present", coverage: "Work-related fatalities inspected by OSHA", url: "https://www.osha.gov/fatalities", status: "Mapped", joinKeys: ["inspection_number", "naics", "state", "event_date"], caveat: "A reported fatality and an inspection outcome are separate facts and must not be conflated." },
  { id: "osha-enforcement", name: "OSHA Inspections, Citations & Violations", domain: "Enforcement", owner: "U.S. Department of Labor", authority: "Primary government", transport: "Bulk ZIP", cadence: "Periodic", history: "1970-present", coverage: "Federal OSHA + participating State Plan records", url: "https://www.osha.gov/data", status: "Needs storage", joinKeys: ["inspection_number", "activity_number", "naics", "state"], caveat: "Open inspections and citation amounts can change after settlements, contests, or corrections." },
  { id: "msha-enforcement", name: "MSHA Mine & Enforcement Data", domain: "Enforcement", owner: "Mine Safety and Health Administration", authority: "Primary government", transport: "Bulk ZIP", cadence: "Periodic", history: "Source dependent", coverage: "U.S. mines, operators, inspections, violations, accidents", url: "https://www.msha.gov/data-reports", status: "Mapped", joinKeys: ["mine_id", "controller_id", "event_date", "state"], caveat: "MSHA identifiers and mining classifications require a separate concordance from NAICS-based market segments." },
  { id: "osha-state-plans", name: "OSHA State Plan Jurisdiction Register", domain: "Enforcement", owner: "U.S. OSHA", authority: "Primary government", transport: "RSS / scan", cadence: "Weekly", history: "Current jurisdiction structure", coverage: "50 states, District of Columbia, Puerto Rico and U.S. Virgin Islands", url: "https://www.osha.gov/stateplans", status: "Ready", joinKeys: ["jurisdiction", "plan_type", "sector_coverage"], caveat: "Private- and public-sector authority must be evaluated separately; excluded federal enclaves and industries require additional review." },
  { id: "bls-soii", name: "BLS Survey of Occupational Injuries and Illnesses", domain: "Injuries", owner: "U.S. Bureau of Labor Statistics", authority: "Primary government", transport: "API", cadence: "Annual", history: "Historical series", coverage: "Generalizable industry injury counts and rates", url: "https://www.bls.gov/iif/", status: "Mapped", joinKeys: ["industry_code", "year", "case_type"], caveat: "Survey estimates, ITA submissions, severe injury reports, and enforcement records use different universes and cannot be summed directly." },
  { id: "bls-qcew", name: "BLS QCEW", domain: "Economy", owner: "U.S. Bureau of Labor Statistics", authority: "Primary government", transport: "CSV slices", cadence: "Quarterly", history: "Recent 5 years via slices; longer via bulk files", coverage: "Employment, establishments, wages, location quotients by NAICS and geography", url: "https://www.bls.gov/cew/additional-resources/open-data/home.htm", status: "Live", joinKeys: ["industry_code", "area_fips", "year", "quarter", "ownership"], caveat: "Suppressed records and NAICS revisions must be retained; growth comparisons require matching geography and ownership." },
  { id: "census-naics", name: "2022 NAICS Classification", domain: "Economy", owner: "U.S. Census Bureau", authority: "Primary government", transport: "File import", cadence: "Revision cycle", history: "Current 2022 hierarchy with historical concordances", coverage: "Sector through six-digit U.S. industry definitions", url: "https://www.census.gov/naics/", status: "Ready", joinKeys: ["naics", "naics_year", "parent_naics"], caveat: "Codes must carry their NAICS vintage; historical data cannot be joined across revisions without a documented concordance." },
  { id: "census-cbp", name: "Census County Business Patterns", domain: "Economy", owner: "U.S. Census Bureau", authority: "Primary government", transport: "API", cadence: "Annual", history: "1986-present", coverage: "Establishments, employment and payroll by NAICS and geography", url: "https://www.census.gov/data/developers/data-sets/cbp-zbp.html", status: "Ready", joinKeys: ["NAICS", "state", "county", "year"], caveat: "Disclosure avoidance and reference-year lag must remain visible in every growth output." },
  { id: "census-bds", name: "Census Business Dynamics Statistics", domain: "Economy", owner: "U.S. Census Bureau", authority: "Primary government", transport: "API", cadence: "Annual", history: "1978-present", coverage: "Firm formation, job creation, entry, exit and growth", url: "https://www.census.gov/programs-surveys/bds/data.API.html", status: "Needs credential", joinKeys: ["NAICS", "state", "year", "firm_size", "firm_age"], caveat: "Some cells are suppressed; flags must be interpreted before zero values are used." },
  { id: "bea-industry", name: "BEA GDP by Industry", domain: "Economy", owner: "U.S. Bureau of Economic Analysis", authority: "Primary government", transport: "API", cadence: "Quarterly", history: "Historical series", coverage: "Value added, gross output and economic contribution by industry", url: "https://apps.bea.gov/api/signup/", status: "Needs credential", joinKeys: ["industry_code", "year", "quarter"], caveat: "BEA industry codes require a documented concordance before joining to six-digit NAICS segments." },
  { id: "federal-register", name: "Federal Register", domain: "Regulations", owner: "GPO / NARA", authority: "Primary government", transport: "API", cadence: "Daily", history: "1994-present", coverage: "Federal rules, proposed rules, notices and dockets", url: "https://www.federalregister.gov/developers/api/v1", status: "Live", joinKeys: ["document_number", "regulation_id_number", "docket_id", "agency"], caveat: "Publication does not by itself establish applicability, effective status, or a final obligation." },
  { id: "ecfr", name: "Electronic Code of Federal Regulations", domain: "Regulations", owner: "GPO / Office of the Federal Register", authority: "Primary government", transport: "API", cadence: "Daily", history: "Current and historical versions", coverage: "Codified federal regulatory text", url: "https://www.ecfr.gov/developers/documentation/api/v1", status: "Ready", joinKeys: ["title", "chapter", "part", "section", "date"], caveat: "eCFR text must be paired with authority, amendment history, and applicability analysis." },
  { id: "epa-echo", name: "EPA ECHO", domain: "Environment", owner: "U.S. EPA", authority: "Primary government", transport: "Web service", cadence: "Source dependent", history: "Program dependent", coverage: "Facility compliance, enforcement and regulated programs", url: "https://echo.epa.gov/tools/web-services", status: "Ready", joinKeys: ["registry_id", "program_id", "facility_name", "state"], caveat: "Current compliance status and historical enforcement are distinct measures with program-specific reporting periods." },
  { id: "state-agency-matrix", name: "State EHS Agency Matrix", domain: "Regulations", owner: "50 states + territories", authority: "Primary government", transport: "RSS / scan", cadence: "Daily / weekly", history: "Rolling 12 months", coverage: "State OSHA Plans, environmental, labor, fire, utility and sector regulators", url: "https://www.osha.gov/stateplans", status: "Mapped", joinKeys: ["jurisdiction", "agency", "document_id", "published_date"], caveat: "There is no single national state-regulation API; every connector needs jurisdiction-specific source and freshness metadata." },
  { id: "sec-edgar", name: "SEC EDGAR", domain: "Corporate Activity", owner: "U.S. Securities and Exchange Commission", authority: "Primary government", transport: "API", cadence: "Near real time", history: "Company filing history", coverage: "8-K, 10-K, 10-Q and other public-company filings", url: "https://www.sec.gov/search-filings/edgar-application-programming-interfaces", status: "Ready", joinKeys: ["cik", "accession_number", "form", "filing_date"], caveat: "Private-company transactions and product announcements may not appear; fair-access headers and rate limits are required." },
  { id: "competitor-official", name: "Competitor Official Source Monitor", domain: "Competitors", owner: "Approved competitor domains", authority: "Official company", transport: "RSS / scan", cadence: "Daily / weekly", history: "Rolling 12 months + retained snapshots", coverage: "Products, modules, releases, newsroom, help center and messaging", url: "https://www.ehs.com/", status: "Mapped", joinKeys: ["company_id", "canonical_url", "retrieved_at", "content_hash"], caveat: "Official claims are Company Statements, not proof of delivery, packaging, adoption, or comparative performance." },
  { id: "ehs-today", name: "EHS Today Watch", domain: "Corporate Activity", owner: "EHS Today", authority: "Approved trade press", transport: "RSS / scan", cadence: "Daily", history: "Rolling 12 months", coverage: "EHS industry news, leadership, products, workplace safety and transactions", url: "https://www.ehstoday.com/", status: "Mapped", joinKeys: ["canonical_url", "published_date", "company_id"], caveat: "Trade-press reporting is secondary evidence and material transactions require confirmation from filings or company statements." },
  { id: "all-injuries-import", name: "All Injuries Controlled Import", domain: "Injuries", owner: "Internal approved dataset", authority: "Internal controlled import", transport: "File import", cadence: "On demand", history: "Full supplied history", coverage: "Pending file validation", url: "", status: "Needs storage", joinKeys: ["source_record_id", "event_date", "naics", "state", "establishment"], caveat: "The file must be profiled, deduplicated, source-attributed, and quarantined before any record becomes publishable." },
];

export const importContract = [
  { field: "source_record_id", required: true, purpose: "Stable deduplication and source trace" },
  { field: "source_id", required: true, purpose: "Source registry relationship" },
  { field: "event_date", required: true, purpose: "Time-series filtering" },
  { field: "naics", required: false, purpose: "Market and segment mapping" },
  { field: "state", required: false, purpose: "Jurisdiction and geography mapping" },
  { field: "establishment", required: false, purpose: "Entity resolution" },
  { field: "event_type", required: true, purpose: "Injury, enforcement, rule, transaction or message change" },
  { field: "source_url", required: true, purpose: "Direct provenance" },
  { field: "retrieved_at", required: true, purpose: "Freshness and reproducibility" },
  { field: "reliability", required: true, purpose: "Publication gating" },
];
